# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
- name: BuildConfiguration
  value: 'Release'
- name: buildOutputFolder
  value: $(Build.ArtifactStagingDirectory)
trigger:
  branches:
    include:
    - refs/heads/master
pool:
  name: 'Rohit'
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Rohit
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      ConnectedServiceName: 1d93d396-d728-4591-8d1a-0092f61e04e8
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      ConnectedServiceName: 1d93d396-d728-4591-8d1a-0092f61e04e8
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      ConnectedServiceName: 1d93d396-d728-4591-8d1a-0092f61e04e8
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      #TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
- job: Deploy
  displayName: 'Deploy to IIS Web Server'
  dependsOn: Job_1
  condition: succeeded()
  pool:
    name: 'Rohit'  # Ensure this is the correct pool with your self-hosted agent
  steps:
    # Step 1: Download build artifacts
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: 'specific'
        project: $(System.TeamProject)
        definition: '5'  # $(Build.DefinitionId)
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(build.artifactstagingdirectory)' #'$(Build.SourcesDirectory)'
    
    # Step 2: Copy Web API files to IIS server folder
    - task: ExtractFiles@1
      displayName: 'Extract published files'
      inputs:
        archiveFilePatterns: '$(build.artifactstagingdirectory)/drop/*.zip'  # Path to the zip file in the 'drop' folder
        destinationFolder: '$(build.artifactstagingdirectory)/extracted'  # Destination folder where files will be extracted
    - task: CopyFiles@2
      displayName: 'Copy Web API files to IIS folder'
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)/extracted' #'$(buildOutputFolder)/webapi'
        Contents: '**'
        TargetFolder: 'C:\inetpub\wwwroot\newfolder'  # Change this path to your IIS folder   
    